### ISSUE TITLE
MOBILE - Refresh nécessaire entre deux vidéos

### ISSUE THREAD

**Issue by Nucleo-rgb** [samet-alaca/fagstream#4]
Une fois la première vidéo visionnée, il est nécessaire de rafraîchir le site pour pouvoir en lire une seconde. En effet une fois l'intro passé, la player reste bloqué et la vidéo ne démarre pas.

**Comment by samet-alaca** [comment]
Résolu sur la 0.5.6.
https://github.com/samet-alaca/fagstream/releases/tag/0.5.6
